comments = [
    'Please explain how Generative AI tools have influenced or transformed your approach to work:',
    'Please explain (Have you received a brief or concept material (ex: drawing) for a production from a director or producer that might have been created using a Generative AI?):',
    "Please explain which AI tools you've proposed:",
    'Please feel free to add further detail: Was it required? Did you agree? Were you compensated? (AI Tool Proposal)',
    'If you have used similar tools or alternatives to those listed above, please feel free to elaborate:',
    'If you have heard of others using similar tools or alternatives to those listed above, please feel free to elaborate:',
    'If you have received training on similar tools or alternatives to those listed above, please feel free to elaborate:',
    "Please describe the reduction in work opportunities you've observed due to AI automation:",
    "Why or why not? (Do you think any new positions should be created within your department for roles involving the use of AI tools and software?)",
    "Suggest any additional priorities not listed above:",
    "What additional support or initiative would you like to see from the Guild in dealing with AI advancements?"
]

allowed_columns = [
    "Language",
    "Primary Job",
    "Secondary Job",
    "District Council",
    "Ethnicity-Broad",
    "FM_Primary_Job",
    "FM_Secondary_Job",
    "FM_Sex",
    "FM_Age",
    "Income_Bracket",
    "Have the latest Generative AI tools and applications – tools like ChatGPT, Runway and Midjourney, or Firefly and Strike-a-Pose in Adobe Creative Suite – influenced the way you approach your work?",
    "Please explain how Generative AI tools have influenced or transformed your approach to work:",
    "How often do you actually use Generative AI in the workplace?",
    "How often do you actually use Generative AI in your personal life (as a hobby or to support other activities)?",
    "When you use AI or Generative AI in your work, you do it:",
    "Have you received a brief or concept material (ex: drawing) for a production from a director or producer that might have been created using a Generative AI?",
    "Have you ever formally proposed the integration of AI (such as Generative AI or other tools) into your workflow to colleagues or supervisors?",
    "Have you been asked to allow your artistic or creative work to be used to train a company’s Generative AI?",
    "Have you observed a reduction in work opportunities due to AI automation in your field?",
    "Are you concerned about the possibility of a reduction in work opportunities due to AI automation in your field within 1 to 5 years?",
    "In your opinion, does Generative AI complement or augment your role?",
    "Do you think any new positions should be created within your department for roles involving the use of AI tools and software?",
    "AI Storyboard Artist: Creating AI-generated visual concepts and storyboards for trailers or films, speeding up pre-production.",
    "AI Content Curator: Managing and refining AI-generated sequences, ensuring the content aligns with creative direction and quality standards.",
    "AI Data Trainer: Teaching AI models specific aesthetic styles or techniques, particularly for film and media production.",
    "Virtual Scene Designer: Using AI to design and optimize virtual environments for live-action or animated sequences.",
    "AI Ethics Consultant: Guiding ethical use of AI in creative industries, ensuring artists and creatives retain control and credit for their work.",
    "AI Workflow Manager: Overseeing AI integrations into production pipelines to streamline tasks like editing, lip-syncing, and scene generation.",
    "AI Prompt Specialist: Entering prompts to generate images and/or video and/or text",
    "Have you considered seeking alternative employment due to the impact, or the coming impact, of AI or Generative AI on your work standards, processes and/or opportunities?",
    "Regular meetings between the DGC and producers/studios about AI usage rules on production",
    "Regular and mandatory transparent reporting on AI use on productions",
    "Receiving adequate compensation to cover the non-creative use of a Generative AI tool or software",
    "Ensuring that members are still properly compensated even when creating work assisted by Generative AI",
    "Receiving compensation for use of production images being entered into a learning model for a Generative AI system (either public or private/studio-owned)",
    "Production training on specific AI tools, relevant to your department and work category",
    "Did you work during the last 12 months?"
]
